name: Build for macOS ARM64

on: [push]

jobs:
  build:
      runs-on: macos-14

          steps:
              - uses: actions/checkout@v3

                  - name: Build binary
                        run: |
                                clang -arch arm64 -framework Foundation -o inject_arm64 inject.m

                                    - name: Upload artifact
                                          uses: actions/upload-artifact@v3
                                                with:
                                                        name: inject_arm64
                                                                path: inject_arm64