name: Build for macOS ARM64

on: [push]

jobs:
  build:
      runs-on: macos-14

      steps:
        - uses: actions/checkout@v3

        - name: Build Binary
          run: | 
            clang -arch arm64 -framework Foundation -o inject_arm64 inject.m

        - name: upload 
          uses: actions/upload-artifact@v4
          with:
            name: inject_arm64
            path: inject_arm64